### ISSUE TITLE
Add setup details/steps done so far to wiki

### ISSUE THREAD

**Issue by greenw0lf** [beeldengeluid/dane-example-worker#11]

**Comment by greenw0lf** [comment]
Link: https://github.com/beeldengeluid/dane-example-worker/wiki/Setting-up-a-new-worker

@Veldhoen @Kathleendeboer @Martaesplo could you check if things are clear and well-structured? I can't really open a PR because the wiki is separate from the repository sadly (unless there is a different way that I'm unaware of).

**Comment by Veldhoen** [comment]
Yes, looks good so far. I moved the bit on linting to a separate section on code style. The Docker-bit can probably be updated after the workshop this Thursday (for instance, to refer to a Dockerfile in this repo once it's there).
