### ISSUE TITLE
Containerize

### ISSUE THREAD

**Issue by Veldhoen** [beeldengeluid/dane-example-worker#3]
- [x] Create Dockerfile
- [x] Check that container runs as expected
- [x] Document in Wiki

**Comment by Veldhoen** [comment]
Do collaborative session on this on the next Squad day > @Veldhoen will prepare

**Comment by greenw0lf** [comment]
@Veldhoen what should be documented about containerization in the wiki? Maybe we can make the slides you prepared for the workshop available somehow? (with view-only permissions)
